### ISSUE TITLE
Add drop tables to clean command

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#320]
- See [this](https://github.com/Maurilearn/learnings/blob/master/shopyoapi/cmd.py#L78) for reference.
- Function to fix is [`clean()`](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/cmd.py#L59) inside [shopyo/shopyoapi/cmd.py](https://github.com/Abdur-rahmaanJ/shopyo/blob/dev/shopyo/shopyoapi/cmd.py)

**Comment by rehmanis** [comment]
- @Abdur-rahmaanJ What is the point of dropping table if you already delete `shopyo.db` like we do? Asking since I do not  know if dropping table after deleting the database does something or not.
- can we also add pycache removal helper to clean such that it clears out all `__pycache__`( currently does not do so)?: Here is the helper function for reference:

```python
from pathlib import Path

def remove_pycache():
    dirpath = Path(__file__).parent.parent.absolute()
    for root, dirs, files in os.walk(dirpath, topdown=False):
        for name in dirs:
            if name == "__pycache__":
                print(os.path.join(root, name))
                shutil.rmtree(os.path.join(root, name))
```

**Comment by Abdur-rahmaanJ** [comment]
@rehmanis in case of mysql or posgres
