### ISSUE TITLE
shopyo initialise does not give same console output as python manage.py initialise

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopcube#413]

**Comment by Shubham-Vishwakarma** [comment]
@Abdur-rahmaanJ 

File "./__main__.py", line 6, in <module>
    from .shopyoapi.file import trycopy
ImportError: attempted relative import with no known parent package

I am getting this on my machine
Python version: 3.8
OS: Ubuntu 20.4

I have remove the first dot to get it working.

I am not sure how is this working in the current build
I haven't changed this import for now
Incase you get this error.
Please remove the prefixed .  from shopyapi

Please try my solution for this issue #413

**Comment by Shubham-Vishwakarma** [comment]
For future reference

Originally was subprocess.run(torun, stdout=subprocess.PIPE) used.
Due to this the output was not redirected back to terminal

One solution will be google how to redirect the subprocess output to terminal
I tried but didn't achieve the desired output
The output was out of sync

Finally I decide to call process method from manage.py directly, instead of using subprocess
And got the expected output
